spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 보내는이메일아이디@gmail.com
    password: 보내는이메일 앱 패스워드
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  mvc:
    view:
      prefix: /templates/
      suffix: .html


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: local