spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /templates
      suffix: .html

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace